################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

#- sections:
#    - title: Getting Started
#      link: docs/getting-started.md
- sections:
    - title: Release notes
      link:
      open: true
      sections:
        - title: Android latest build
          sections:
            - title: ZelleSDK_V_1.5.1
              link: docs/release-notes/Android/updated-kotlin/ZelleSDK_V_1.5.1.md
            - title: ZelleSDK_V_2.1.3
              link: docs/release-notes/Android/downgraded-kotlin/ZelleSDK_V_2.1.3.md

        - title: iOS latest build
          sections:
            - title: ZelleSDK_V_1.4.5
              link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md

- sections:
    - title: Version History
      link:
      open: true
      sections:
        - title: Android
          link:
          sections:
            - title: Updated Kotlin
              sections:
              - title: ZelleSDK_V_1.5.0
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.5.0.md
              - title: ZelleSDK_V_1.4.9
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.9.md
              - title: ZelleSDK_V_1.4.8
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.8.md
              - title: ZelleSDK_V_1.4.7
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.7.md
              - title: ZelleSDK_V_1.4.6
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.6.md
              - title: ZelleSDK_V_1.4.5
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.5.md
              - title: ZelleSDK_V_1.4.4
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.4.md
              - title: ZelleSDK_V_1.4.3
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.3.md
              - title: ZelleSDK_V_1.4.2
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.2.md
              - title: ZelleSDK_V_1.4.1
                link: docs/version-history/Android/updated-kotlin/ZelleSDK_V_1.4.1.md
            - title: Downgraded Kotlin
              sections:
              - title: ZelleSDK_V_2.1.2
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.1.2.md
              - title: ZelleSDK_V_2.1.1
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.1.1.md
              - title: ZelleSDK_V_2.1.0
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.1.0.md
              - title: ZelleSDK_V_2.0.9
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.9.md
              - title: ZelleSDK_V_2.0.8
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.8.md
              - title: ZelleSDK_V_2.0.7
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.7.md
              - title: ZelleSDK_V_2.0.6
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.6.md
              - title: ZelleSDK_V_2.0.5
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.5.md
              - title: ZelleSDK_V_2.0.4
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.4.md
              - title: ZelleSDK_V_2.0.3
                link: docs/version-history/Android/downgraded-kotlin/ZelleSDK_V_2.0.3.md

        - title: iOS
          sections:
            - title: ZelleSDK_V_1.4.4
              link: docs/version-history/iOS/ZelleSDK_V_1.4.4.md
            - title: ZelleSDK_V_1.4.3
              link: docs/version-history/iOS/ZelleSDK_V_1.4.3.md
            - title: ZelleSDK_V_1.4.2
              link: docs/version-history/iOS/ZelleSDK_V_1.4.3.md
            - title: ZelleSDK_V_1.4.1
              link: docs/version-history/iOS/ZelleSDK_V_1.4.3.md

- sections:
    - title: Supporting Platforms
      link:
      open: true
      sections:
        - title: Android
          sections:
            - title: Kotlin
              link: docs/supporting-documents/kotlin.md
            - title: Java
              link: docs/supporting-documents/java.md

        - title: iOS
          sections:
            - title: Swift
              link: docs/supporting-documents/swift.md
            - title: Objective C
              link: docs/supporting-documents/objectivec.md

        - title: Xamarin
          sections:
            - title: Integration Steps
              link: docs/supporting-documents/xamarin.md
            - title: DLL Files
              sections:
                - title: Android
                  sections:
                  - title: ZelleSDK_V_1.0.0
                    link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md
                  - title: ZelleSDK_V_1.0.1
                    link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md

                - title: iOS
                  sections:
                  - title: ZelleSDK_V_1.0.0
                    link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md
                  - title: ZelleSDK_V_1.0.1
                    link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md

        - title: Flutter
          sections:
            - title: Integration Steps
              link: docs/supporting-documents/flutter.md

        - title: ReactNative
          sections:
            - title: Integration Steps
              link: docs/supporting-documents/react-native.md

        - title: Cordova
          sections:
            - title: Integration Steps
              link: docs/supporting-documents/cordova.md
            - title: Plugin Files
              sections:
                - title: ZelleSDK_V_1.0.0
                  link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md
                - title: ZelleSDK_V_1.0.1
                  link: docs/release-notes/iOS/ZelleSDK_V_1.4.5.md

        - title: Kony
          sections:
            - title: Integration Steps
              link: docs/supporting-documents/kony.md






     
