################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Zelle SDK
  productionDescription: ZelleSDK offers the flexibility to access the mobile device capabilities for Zelle® UI (e.g., contact list, camera, photo gallery, and sharing).
  getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Android SDK - Upgraded Kotlin
    groupName: Guides
    description: The Kotlin programming language was used to create the SDK, which has a version of 1.5.10.
    relatedDocs:
      - relatedDoc:
        title: Latest Zelle SDK
        description: The latest Zelle SDK version is V_1.5.1.  It will support both kotlin and java application.
        link: ./docs/release-notes/Android/updated-kotlin/ZelleSDK_V_1.5.1.md
      - relatedDoc:
        title: Kotlin Integration Document
        description: Technical integration guide for kotlin
        link: ./docs/supporting-documents/kotlin.md
      - relatedDoc:
        title: Java Integration Document
        description: Technical integration guide for java
        link: ./docs/supporting-documents/java.md
  - title: Android SDK - Downgraded Kotlin
    groupName: Guides
    description: The Kotlin programming language was used to create the SDK, which has a version of 1.3.72.
    relatedDocs:
      - relatedDoc:
        title: Latest Zelle SDK
        description: The latest Zelle SDK version is V_2.1.3.  It will support both kotlin and java application.
        link: ./docs/release-notes/Android/downgraded-kotlin/ZelleSDK_V_2.1.3.md
      - relatedDoc:
        title: Kotlin Integration Document
        description: Technical integration guide for kotlin
        link: ./docs/supporting-documents/kotlin.md
      - relatedDoc:
        title: Java Integration Document
        description: Technical integration guide for java
        link: ./docs/supporting-documents/java.md
  - title: iOS SDK
    groupName: Guides
    description: The Swift programming language was used to create the SDK, which has a version of .
    relatedDocs:
      - relatedDoc:
        title: Latest Zelle SDK
        description: The latest Zelle SDK version is 1.4.5.  It will support both swift and objective-C application.
        link: ./docs/release-notes/iOS/ZelleSDK_V_1.4.5.md
      - relatedDoc:
        title: Swift Integration Document
        description: Technical integration guide for swift
        link: ./docs/supporting-documents/swift.md
      - relatedDoc:
        title: Object-C Integration Document
        description: Technical integration guide for objective-C
        link: ./docs/supporting-documents/objectivecs.md
